### ISSUE TITLE
只有一些文字有正常显示中文，然后其他地方都是空白，跟着教程做完可以做的东西了

### ISSUE THREAD

**Issue by Mr-small-2-six** [Dclef/renpy-tl#10]
SourceHanSansLite.ttf也放了gui.py也改了，可以做的也做了，编程小白，不知道哪里还可以改
![Base Profile Screenshot 2023 06 20 - 23 34 48 38](https://github.com/Dclef/renpy-tl/assets/122677668/bdad1cad-5bb6-484f-be67-54ab52026a14)

![image](https://github.com/Dclef/renpy-tl/assets/122677668/7a950f74-400d-4fcb-8e10-853d9e0c5497)
选单上也只有几个正常显示，然后全部都是空白

# TODO: Translation updated at 2023-06-20 00:28

# game/ch/aletta/base.rpy:194
translate chinese aletta_bye_e350a6b2:

    # aletta.say "I should probably go to bed."
    aletta.say "我应该去睡觉了。"

# game/ch/aletta/base.rpy:198
translate chinese aletta_bye_6782d73f:

    # aletta.say "I've got classes right now, I should probably get going."
    aletta.say "我现在有课，我应该走了。"

ti里面的rpy大概没有改错的

**Comment by Dclef** [comment]
换字体，在文档中的Q&A中可找到，你没找全，要全局搜索字体进行替换或者进群用脚本替换。

**Comment by Mr-small-2-six** [comment]
是说gui里的吗？
我换了，用了renpy skd里的SourceHanSansLite.ttf，也在google上下载了不同版本的SourceHanSansLite.ttf还是无法显示

define gui.default_font = "SourceHanSansLite.ttf"


define gui.name_font = "SourceHanSansLite.ttf"


define gui.interface_font = "SourceHanSansLite.ttf"

**Comment by Mr-small-2-six** [comment]
[common.txt](https://github.com/Dclef/renpy-tl/files/11815572/common.txt)
里面的格式应该没错里面
想快速保存，返回之类的中文字还是在游戏的正下方显示

非常感谢，抽时间回答我的问题

**Comment by Dclef** [comment]
> 是说gui里的吗？ 我换了，用了renpy skd里的SourceHanSansLite.ttf，也在google上下载了不同版本的SourceHanSansLite.ttf还是无法显示
> 
> define gui.default_font = "SourceHanSansLite.ttf"
> 
> define gui.name_font = "SourceHanSansLite.ttf"
> 
> define gui.interface_font = "SourceHanSansLite.ttf"

首先你定义字体定义不全，其次除了gui里面的还有其他文件有其他字体你需要用vscode或者其他编辑器全局搜索ttf或者otf替换

**Comment by Mr-small-2-six** [comment]
类似这几种的ttf都更换吗？  
  
    frame:
            background None
            xfill True
            yfill True
            xpos 10
            ypos 10
            text what font "ui/Vajsko/fonts/Exo_2/Exo2-Regular.ttf" size 23 color "#ffffff" id "what" align 0.0,0.0

style custom_button_text is text:
    font "ui/Vajsko/fonts/Exo_2/Exo2-Bold.ttf"
    color "#ffffff"
    
    就任何文件有出现ttf的地方都更换成SourceHanSansLite.ttf这样我大概明白了，我去尝试下
    非常感谢
