### ISSUE TITLE
翻译文件汉化完成后，选项没有变化

### ISSUE THREAD

**Issue by ghost** [Dclef/renpy-tl#11]
大佬你好，请问一下这种情况怎么办！
tl文件夹里的已经翻译完了，打开游戏后，对话是正常的，但是选项按钮的文字没变，
old  "Leave"
new "离开"

游戏里还是显示的Leave

期待大佬的回答...

**Comment by Dclef** [comment]
大概率是因为用正则生成的tl文件夹并没有匹配到游戏的按钮选项，这个时候你需要取翻译源码，把源码中的英文替换才行。

**Comment by ghost** [comment]
> 大概率是因为用正则生成的tl文件夹并没有匹配到游戏的按钮选项，这个时候你需要取翻译源码，把源码中的英文替换才行。

好的,谢谢大佬的回复
