### ISSUE TITLE
用 RAPT 打包成 Android 版怎么换图标和启动图

### ISSUE THREAD

**Issue by HuaJi2333DaDa** [Dclef/renpy-tl#5]
如题，想在打包时就换掉默认图标和启动图。打完包再换签名就没了😂

**Comment by HuaJi2333DaDa** [comment]
找到了😂

**Comment by Dclef** [comment]
感谢提供issues，已更新，可看[6.6](https://github.com/Dclef/renpy-tl#66-%E6%88%91%E6%83%B3%E6%9B%BF%E6%8D%A2%E5%9B%BE%E6%A0%87%E5%A6%82pc%E5%92%8C%E5%AE%89%E5%8D%93%E8%AF%A5%E5%A6%82%E4%BD%95%E6%9B%BF%E6%8D%A2)
