### ISSUE TITLE
【提问】游戏内界面不显示中文。

### ISSUE THREAD

**Issue by YingJo** [Dclef/renpy-tl#6]
大佬您好~
我是个没有任何编码基础的小白，因为找不到汉化文件，不得不自给自足。
我根据您的教程，重复了整个教程流程对我喜欢的游戏进行汉化，但是失败了……打开游戏后，界面上是全空的，没有显示任何文字，包括英文。
后面我开始啃官网的中文文档，更改了部分style.rpy文件，好像有了一些用……界面上出现了“SourceHanSansLite.ttf”的……英文字。我将所有在tl文件夹内的rpy文件都翻译了，想不通为什么会只出现英文，不出现中文。
我在renpy翻译界面上无意中发现了“合并字串翻译”的按钮，抱着试一试的心态按了，居然真的管用了，控制台（游戏开始界面，我不确定能不能这样称呼）上的文字都被成功翻译成了中文，但是新加入的语言那一联整个消失了，我能感到按钮还在，因为能靠盲点回到英文，页面那个位置什么也没显示——并且回到英文界面，显示就正常了。
最主要的是，游戏内对话和选项框仍旧没有任何中文文本显示，全是空的。
我试过搜索gui、screens文档里所有带font和.tff字串的内容，把他们替换成“SourceHanSansLite.ttf”但也失败了，这好像跟更改style.rpy文件得到的结果是一样的。

感谢您耐心看到这里
期待您的恢复

ps：我刚刚注册github，还不是很熟练，如过您能给我一封邮件或者加下QQ就更感谢啦XD
email：921508500@qq.com  QQ:921508500

我也会重复刷新github的XD

**Comment by Dclef** [comment]
感谢您看完我的教程，我猜您是从6.7中点击进来的，也就证明您讲常见问题也看完了一遍。

**Comment by YingJo** [comment]
嗯嗯，是的。6.3有解决方块字的方法，但我甚至没有任何东西显示……

**Comment by Dclef** [comment]
但您的提问有些地方我感觉有点疑惑，就是界面上出现了“SourceHanSansLite.ttf”的……英文字是什么意思？
显示空白感觉很奇怪，按道理来讲是没问题的。我猜游戏的翻译文件其实没有扫描到，或者来说翻译到生成了文件，但由于没有翻译或者没有找到显示的是空字符串导致界面空白。请尝试一下重新生成翻译，取消为翻译生成空字符串的按钮。再打开游戏是否可以显示英文，再翻译成中文逐一排查。
另外您用QQ注册的github的话，issue更新会自动发邮件到您的QQ邮箱的 XD

**Comment by Dclef** [comment]
由于你长时间未回复，此issue关闭
