### ISSUE TITLE
百度的翻译脚本其实可以用Translator++也在用得那个API.

### ISSUE THREAD

**Issue by daiaji** [Dclef/renpy-tl#7]
https://github.com/TimLuo465/baidu-translate-api
没啥限制。
我自己申请的API,搞一个游戏，字数用完了。

**Comment by Dclef** [comment]
你可以看我的tran.py

**Comment by Dclef** [comment]
你可以看我的tran.py https://github.com/Dclef/renpy-tl/blob/master/tran.py
是基于百度的api翻译的
另外百度标准版没有字数限制，QPS限制为1，但够用。

**Comment by daiaji** [comment]
@Dclef 现在要用了，高级和免费API都受限了。
