### ISSUE TITLE
[提问] 同一个文本需要翻译成不同意思怎么做

### ISSUE THREAD

**Issue by KateJohn** [Dclef/renpy-tl#8]
大佬您好~
普通文本是看translate后这串16进制数进行定位，可以重复
![image](https://user-images.githubusercontent.com/27270609/174534264-d194f4cd-e48a-47f2-b284-04767c1087b0.png)
其他一些文本，如选项和作者自定义文本就不可以重复
![v2-22efb9b6f94ce9f9e1012fecd9593190_r](https://user-images.githubusercontent.com/27270609/174534460-e28715eb-2f70-4a6a-bbb5-7581aade9554.jpg)
我能想到的一个办法是修改原文，加一些标识符，但有没有不修改原文的办法呢？

感谢您耐心看到这里
期待您的恢复（没错，抄了另一个issue的格式）

**Comment by Dclef** [comment]
我只知道行数定位 vscode直接ctrl+g 输入行数就行了
同一个文本翻译不同意思直接添加 \n 做成双语版本就行了，详情可看表格汉化
你可以使用Translator++打上不同颜色的tag标签如图
![image](https://user-images.githubusercontent.com/42974381/174555835-80ed3d13-0ab6-4253-b55b-d563a30f8bab.png)
但Translator++会将一些源码给翻译掉你需要自己去排查

**Comment by KateJohn** [comment]
> 同一个文本翻译不同意思直接添加 \n 做成双语版本就行了，详情可看表格汉化

可以具体一点吗，我不是很理解

> 由于是机翻，本人想中英对照就原英文加个换行符(\n)一起替换回去，具体方法加个&合连接表格即可（注意：对话可以加换行符，new”语句加换行符容易出错，本模板只需手动删除\n即可）

而且需要的不是双语版本，比如‘yeah’有时需要翻成‘是的’，有时是‘好的’
谢谢大佬

**Comment by KateJohn** [comment]
哦，双语是保留英语原版的意思是吗，那应该要双语版本的

**Comment by Dclef** [comment]
> 可以具体一点吗，我不是很理解

请下载第5大点的表格汉化文件压缩包以及教程视频
链接https://dclef.lanzouj.com/inxOS03ha69g
如图
![image](https://user-images.githubusercontent.com/42974381/174563146-a32715fe-cb22-49d1-98f4-7cc16fdaafad.png)


> 而且需要的不是双语版本，比如‘yeah’有时需要翻成‘是的’，有时是‘好的’ 

这需要你自己去人工润色，根据情景和语境不同翻译不同的信息


> 哦，双语是保留英语原版的意思是吗，那应该要双语版本的

是保留英文原版的意思

**Comment by KateJohn** [comment]
> ![](https://user-images.githubusercontent.com/42974381/174563146-a32715fe-cb22-49d1-98f4-7cc16fdaafad.png)

不是这种文本，像下面这样提取的作者自定义的文本
![image](https://user-images.githubusercontent.com/27270609/174564982-685e3a3b-c3ab-42ac-97a8-70a5dd87da96.png)

就会报这种错
![image](https://user-images.githubusercontent.com/27270609/174564845-9e5a6093-6ec0-4231-9916-1faeaf8811f8.png)

**Comment by Dclef** [comment]
这是语句导出的时候会多出几个无意义的重复语句的问题，删除其中一个重复的即可。

**Comment by KateJohn** [comment]
这种时候想要翻译出不同的意思，有什么办法吗

**Comment by Dclef** [comment]
> 这种时候想要翻译出不同的意思，有什么办法吗

没有，这是单纯多出的毫无意义的重复语句，需要删掉。而且翻译以后出报你刚刚的错，报错内容是此文本已存在。

**Comment by KateJohn** [comment]
就是说除了修改原文，这样的句子只能翻译成一样的，是吗？

**Comment by Dclef** [comment]
请问你这重复的语句不删除能运行吗？你这报错的原因是多个相同的翻译指向一个所以要报错，你可以去尝试翻译不同的意思看会不会报错或者有没有效果。除非你修改源代码去增加一句这样的话。

**Comment by KateJohn** [comment]
好的，知道了，谢谢大佬
