### ISSUE TITLE
已汉化的游戏，如何导出原文译文映射rpy文件(tl目录下)？

### ISSUE THREAD

**Issue by tooyangtoonaive** [Dclef/renpy-tl#9]
使用unrpyc得到的tl/*.rpy文件格式为

```
translate chinese airport_772afa68:

    "机场有不少人。"
```

而不是这种映射关系明确的格式
![图片](https://user-images.githubusercontent.com/19810827/179778518-37369aa2-c7e1-4d7c-8b75-c11ca96447db.png)

**Comment by Dclef** [comment]
![image](https://user-images.githubusercontent.com/42974381/179892774-2fd3a0b1-56ea-4963-973b-b61619556006.png)
![image](https://user-images.githubusercontent.com/42974381/179892812-b60a9450-8d4a-4cc8-9b44-29ee74d4b2e0.png)
没有导出翻译的功能 只有导出原文和将翻译的文件合并到另一个工程的功能

**Comment by tooyangtoonaive** [comment]
> ![image](https://user-images.githubusercontent.com/42974381/179892774-2fd3a0b1-56ea-4963-973b-b61619556006.png) ![image](https://user-images.githubusercontent.com/42974381/179892812-b60a9450-8d4a-4cc8-9b44-29ee74d4b2e0.png) 没有导出翻译的功能 只有导出原文和将翻译的文件合并到另一个工程的功能

这方法我试过了。你的图2，大部分文本不能合并。

**Comment by Dclef** [comment]
我的意思是文本导出不了 你所说的明确关系是必须存在的 如
![image](https://user-images.githubusercontent.com/42974381/180131419-613aaebc-0a4b-4402-94e9-6a97403cc92d.png)
或者
![image](https://user-images.githubusercontent.com/42974381/180131433-bafb8d1e-cd00-483a-955b-7c356d8f64a9.png)
但你可以将此rpy文件删除以后再去反编译一遍 反编译后的rpy文件就没有注释 如
![image](https://user-images.githubusercontent.com/42974381/180131617-d00bf2c3-0de1-4953-8578-bf2f809cfac3.png)
或者
![image](https://user-images.githubusercontent.com/42974381/180131665-5769316a-e9ce-4c37-8742-8a0c9d459d40.png)
如果你需要去合并文本可以使用一个[小工具](https://dclef.lanzouj.com/iovzS085lckh) 但不能合并成纯文本格式的翻译原文
只能将原文全部合并一遍 关于renpysdk里面的导出合并是没有用的 sdk只能导出原文文本
